language: node_js
node_js:
  - "8"
dist: trusty
services:
  - mongodb
env:
  _NODE_ENV=ci PORT=3000 SECRET=12345
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm build
script:
  - nohup npm run start & 
  - sleep 3
  - npm run test